---
- name: Create node_exporter group
  group:
    name: node_exporter
    
- name: Create node_exporter user
  user:
    name: node_exporter
    system: yes
    shell: /bin/false
    state: present

- name: Deploy node_exporter binary
  copy:
    src: files/node_exporter
    dest: /usr/local/bin/node_exporter
    force: yes
    mode: '755'
  notify: daemon-reload

- name: Flush handlers
  meta: flush_handlers

- name: Deploy Systemd service
  blockinfile: 
    path: /etc/systemd/system/node_exporter.service
    create: yes
    block: |
      [Unit]
      Description=Node Exporter
      After=network.target
      
      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter
      
      [Install]
      WantedBy=multi-user.target	
  notify: daemon-reload

- name: Ensure service enabled and running
  systemd:
    name: node_exporter.service
    state: started
    enabled: true



